services:
  # ---------- MySQL Database for Zabbix ----------
  mysql-server:
    image: mysql:8.0
    container_name: zabbix-mysql
    restart: always
    environment:
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - zabbix_mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zabbix-network

  # ---------- Zabbix Server ----------
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-6.4-latest
    container_name: zabbix-server
    restart: always
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
      ZBX_STARTPOLLERS: 5
      ZBX_STARTPOLLERSUNREACHABLE: 1
      ZBX_STARTTRAPPERS: 5
      ZBX_STARTPINGERS: 1
      ZBX_STARTDISCOVERERS: 1
      ZBX_STARTHTTPPOLLERS: 1
    ports:
      - "10051:10051"
    volumes:
      - zabbix_server_data:/var/lib/zabbix
      - zabbix_server_scripts:/usr/lib/zabbix/alertscripts
      - zabbix_server_modules:/var/lib/zabbix/modules
    depends_on:
      mysql-server:
        condition: service_healthy
    networks:
      - zabbix-network

  # ---------- Zabbix Web (Frontend) ----------
  zabbix-web:
    image: zabbix/zabbix-web-apache-mysql:alpine-6.4-latest
    container_name: zabbix-web
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix_password
      MYSQL_ROOT_PASSWORD: root_password
      PHP_TZ: "America/Sao_Paulo"
    ports:
      - "8081:8080"
    depends_on:
      - mysql-server
      - zabbix-server
    networks:
      - zabbix-network

  # ---------- Zabbix Agent 2 ----------
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    container_name: zabbix-agent2
    restart: always
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      ZBX_PASSIVE_ALLOW: "true"
      ZBX_ACTIVE_ALLOW: "true"
      ZBX_SERVERS: "0.0.0.0/0"
      ZBX_SERVERACTIVE: "0.0.0.0/0"
      ZBX_ENABLEREMOTECOMMANDS: 1
      ZBX_LOGREMOTECOMMANDS: 1
    ports:
      - "10050:10050"
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network

volumes:
  zabbix_mysql_data:
    driver: local
  zabbix_server_data:
    driver: local
  zabbix_server_scripts:
    driver: local
  zabbix_server_modules:
    driver: local

networks:
  zabbix-network:
    driver: bridge