apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-agent2
  labels:
    app: zabbix-agent2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-agent2
  template:
    metadata:
      labels:
        app: zabbix-agent2
    spec:
      containers:
      - name: zabbix-agent2
        image: zabbix/zabbix-agent2:alpine-6.4-latest
        env:
        - name: ZBX_HOSTNAME
          value: "zabbix-agent2"
        - name: ZBX_SERVER_HOST
          value: "0.0.0.0/0"
        - name: ZBX_SERVER_PORT
          value: "10051"
        - name: ZBX_PASSIVE_ALLOW
          value: "true"
        - name: ZBX_ACTIVE_ALLOW
          value: "false"
        - name: ZBX_SERVERS
          value: "0.0.0.0/0"
        - name: ZBX_SERVERACTIVE
          value: ""
        - name: ZBX_ENABLEREMOTECOMMANDS
          value: "1"
        - name: ZBX_LOGREMOTECOMMANDS
          value: "1"
        - name: ZBX_LISTENPORT
          value: "10050"
        - name: ZBX_STARTAGENTS
          value: "3"
        - name: ZBX_TIMEOUT
          value: "3"
        - name: ZBX_METADATA
          value: "Linux Docker"
        ports:
        - containerPort: 10050

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-agent2-svc
spec:
  selector:
    app: zabbix-agent2
  ports:
  - port: 10050
    targetPort: 10050
  type: ClusterIP
