apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-scripts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-server-modules-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  labels:
    app: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-mysql:alpine-6.4-latest
        env:
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: DB_SERVER_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: MYSQL_ROOT_PASSWORD
        - name: ZBX_STARTPOLLERS
          value: "5"
        - name: ZBX_STARTPOLLERSUNREACHABLE
          value: "1"
        - name: ZBX_STARTTRAPPERS
          value: "5"
        - name: ZBX_STARTPINGERS
          value: "1"
        - name: ZBX_STARTDISCOVERERS
          value: "1"
        - name: ZBX_STARTHTTPPOLLERS
          value: "1"
        ports:
        - containerPort: 10051
        volumeMounts:
        - name: server-data
          mountPath: /var/lib/zabbix
        - name: server-scripts
          mountPath: /usr/lib/zabbix/alertscripts
        - name: server-modules
          mountPath: /var/lib/zabbix/modules
      volumes:
      - name: server-data
        persistentVolumeClaim:
          claimName: zabbix-server-data-pvc
      - name: server-scripts
        persistentVolumeClaim:
          claimName: zabbix-server-scripts-pvc
      - name: server-modules
        persistentVolumeClaim:
          claimName: zabbix-server-modules-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-svc
spec:
  selector:
    app: zabbix-server
  ports:
  - port: 10051
    targetPort: 10051
    nodePort: 30051
  type: NodePort
