apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  labels:
    app: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-apache-mysql:alpine-6.4-latest
        env:
        - name: ZBX_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: ZBX_SERVER_HOST
        - name: DB_SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: DB_SERVER_HOST
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: zabbix-configmap
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secret
              key: MYSQL_ROOT_PASSWORD
        - name: PHP_TZ
          value: "America/Sao_Paulo"
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: zabbix-web-svc
spec:
  selector:
    app: zabbix-web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30081
  type: NodePort
