apiVersion: batch/v1
kind: Job
metadata:
  name: catalogo-migrations-job
spec:
  template:
    metadata:
      labels:
        app: catalogo-migrations-pod
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            [
              "sh",
              "-c",
              "until nc -z catalogo-mysql-svc 3306; do echo waiting for mysql; sleep 2; done;",
            ]
      containers:
        - name: catalogo-migrations-pod
          image: catalogo-migrations-image
          imagePullPolicy: Never
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "$(ASPNETCORE_ENVIRONMENT)"
            - name: "CONNECTION_STRING"
              value: "Server=catalogo-mysql-svc;Database=$(DB_DATABASE);User=$(DB_USER);Password=$(DB_PASSWORD);Port=$(DB_PORT);"
          envFrom:
            - configMapRef:
                name: mysql-configmap
            - secretRef:
                name: mysql-secret
      restartPolicy: OnFailure
  backoffLimit: 4
