apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  DB_DATABASE: "fasttech_catalogo"
  DB_PORT: "3306"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  RABBITMQ_HOST: "rabbitmq-svc"

