apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
stringData:
  DB_USER: "root"
  DB_PASSWORD: "123456"

---

apiVersion: v1
kind: Secret
metadata:
  name: zabbix-secret
stringData:
  MYSQL_USER: "zabbix"
  MYSQL_PASSWORD: "zabbix_password"
  MYSQL_ROOT_PASSWORD: "root_password"

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GF_SECURITY_ADMIN_USER: "admin"
  GF_SECURITY_ADMIN_PASWORD: "admin"